<template>
  <div class="h-64 grid grid-rows-3 grid-cols-3 gap-4">
    <div>
      <button
        class="
          border-2
          py-2
          w-28
          bg-red-500
          border-red-500
          hover:bg-white
          text-white
          hover:text-red-500
          font-bold
        "
        type="button"
      >
        Disconnect
      </button>
    </div>
    <div>1</div>
    <div>1</div>
    <div>1</div>
  </div>
</template>
